from app.database.service.user_service import UserService
from app.database.service.app_info_service import AppInfoService
from app.database.service.app_types_service import AppTypesService
from app.database.service.app_versions_service import AppVersionsService
from app.database.service.developers_service import DevelopersService
from app.database.service.licenses_service import LicensesService
from app.database.service.screenshots_service import ScreenshotsService
from app.database.service.user_app_service import UserAppService
from app.database.service.ratings_reviews_service import RatingsReviewsService